// Proyecto  : Sistema de Gestión de Cobros QR — BCP
// Servicio  : ReportService
// Iteración : Fase 3 — Construcción, Iteración 1
// Trazab.   : [R-06] → [CU-06] → [ReportsController] → [ReportTests]
// Autor     : [Tesista]
// Fecha     : 2026
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QRPayments.ReportService.Domain.Entities;
using QRPayments.ReportService.Domain.Enums;
using QRPayments.ReportService.Infrastructure.Data;

namespace QRPayments.ReportService.Controllers;

[ApiController]
[Route("api/reports")]
[Authorize]
public class ReportsController : ControllerBase
{
    private readonly AppDbContext _db;
    private readonly IHttpClientFactory _httpFactory;
    private readonly ILogger<ReportsController> _logger;

    public ReportsController(AppDbContext db, IHttpClientFactory httpFactory, ILogger<ReportsController> logger)
    {
        _db = db;
        _httpFactory = httpFactory;
        _logger = logger;
    }

    [HttpGet]
    public async Task<IActionResult> GetAll(CancellationToken ct)
    {
        var reports = await _db.Reports
            .OrderByDescending(r => r.GeneratedAt)
            .Select(r => new ReportDto(r.Id, r.Type.ToString(), r.StartDate, r.EndDate, r.GeneratedAt, r.GeneratedBy))
            .ToListAsync(ct);
        return Ok(reports);
    }

    [HttpPost("generate")]
    public async Task<IActionResult> Generate([FromBody] GenerateReportRequest request, CancellationToken ct)
    {
        var generatedBy = User.Identity?.Name ?? "system";

        var report = new Report
        {
            Type = request.Type,
            StartDate = request.StartDate,
            EndDate = request.EndDate,
            GeneratedBy = generatedBy
        };

        // Fetch transaction data from TransactionService
        List<TransactionSummaryItem> transactions = new();
        try
        {
            var client = _httpFactory.CreateClient("TransactionService");
            if (request.CompanyId.HasValue)
            {
                var resp = await client.GetAsync($"/api/transactions?companyId={request.CompanyId.Value}", ct);
                if (resp.IsSuccessStatusCode)
                {
                    var body = await resp.Content.ReadAsStringAsync(ct);
                    transactions = System.Text.Json.JsonSerializer.Deserialize<List<TransactionSummaryItem>>(body,
                        new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? new();
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not fetch transactions for report");
        }

        _db.Reports.Add(report);
        await _db.SaveChangesAsync(ct);

        return Ok(new GeneratedReportDto(
            report.Id, report.Type.ToString(), report.StartDate, report.EndDate,
            report.GeneratedAt, report.GeneratedBy,
            transactions.Count,
            transactions.Sum(t => t.Amount)));
    }

    [HttpGet("{id:guid}/export")]
    public async Task<IActionResult> Export(Guid id, [FromQuery] string format = "excel", CancellationToken ct = default)
    {
        var report = await _db.Reports.FindAsync(new object[] { id }, ct);
        if (report is null) return NotFound();

        if (format.Equals("pdf", StringComparison.OrdinalIgnoreCase))
        {
            var html = BuildHtmlReport(report);
            var bytes = Encoding.UTF8.GetBytes(html);
            return File(bytes, "text/html", $"report-{id}.html");
        }
        else
        {
            // Excel: simple CSV as a substitute (no heavy library)
            var csv = BuildCsvReport(report);
            var bytes = Encoding.UTF8.GetBytes(csv);
            return File(bytes, "text/csv", $"report-{id}.csv");
        }
    }

    private static string BuildHtmlReport(Report report)
    {
        return $"""
            <!DOCTYPE html>
            <html>
            <head><meta charset="utf-8"/><title>Report {report.Id}</title></head>
            <body>
            <h1>QRPayments Report</h1>
            <table border="1">
              <tr><th>Field</th><th>Value</th></tr>
              <tr><td>ID</td><td>{report.Id}</td></tr>
              <tr><td>Type</td><td>{report.Type}</td></tr>
              <tr><td>Period</td><td>{report.StartDate:yyyy-MM-dd} → {report.EndDate:yyyy-MM-dd}</td></tr>
              <tr><td>Generated At</td><td>{report.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC</td></tr>
              <tr><td>Generated By</td><td>{report.GeneratedBy}</td></tr>
            </table>
            </body>
            </html>
            """;
    }

    private static string BuildCsvReport(Report report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Field,Value");
        sb.AppendLine($"ID,{report.Id}");
        sb.AppendLine($"Type,{report.Type}");
        sb.AppendLine($"StartDate,{report.StartDate:yyyy-MM-dd}");
        sb.AppendLine($"EndDate,{report.EndDate:yyyy-MM-dd}");
        sb.AppendLine($"GeneratedAt,{report.GeneratedAt:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"GeneratedBy,{report.GeneratedBy}");
        return sb.ToString();
    }
}

public record GenerateReportRequest(ReportType Type, DateTime StartDate, DateTime EndDate, Guid? CompanyId);
public record ReportDto(Guid Id, string Type, DateTime StartDate, DateTime EndDate, DateTime GeneratedAt, string GeneratedBy);
public record GeneratedReportDto(Guid Id, string Type, DateTime StartDate, DateTime EndDate, DateTime GeneratedAt, string GeneratedBy, int TransactionCount, decimal TotalAmount);
public record TransactionSummaryItem(Guid Id, decimal Amount, string Status);
